spring:
  application:
    name: auth

jwt:
  secret: ${JWT_SECRET:mysecretkey}
  expiration: ${JWT_EXPIRATION:3600000} # 1 hour in milliseconds
  refreshExpiration: ${JWT_REFRESH_EXPIRATION:86400000} # 24 hours in milliseconds
