spring:
  application:
    name: auth

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/restaurantdb}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true

jwt:
  secret: ${JWT_SECRET:mysecretkey}
  expiration: ${JWT_EXPIRATION:3600000} # 1 hour in milliseconds
  refreshExpiration: ${JWT_REFRESH_EXPIRATION:86400000} # 24 hours in milliseconds
