services:

  eurekaserver:
    build:
      context: ../apps/eurekaserver
    ports:
      - "8761:8761"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: restaurantdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:noble
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10

  user:
    build:
      context: ../apps/user
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_URL=jdbc:mysql://mysql:3306/restaurantdb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - EUREKA_SERVER_URL=http://eurekaserver:8761/eureka/
    depends_on:
      - eurekaserver
      - mysql 


  restaurantlisting:
    build:
      context: ../apps/restaurantListing
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_URL=jdbc:mysql://mysql:3306/restaurantdb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - EUREKA_SERVER_URL=http://eurekaserver:8761/eureka/
    depends_on:
      - eurekaserver
      - mysql 

  order:
    build:
      context: ../apps/order
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATABASE_URL: mongodb://root:password@mongodb:27017/restaurantdb?authSource=admin
      EUREKA_SERVER_URL: http://eurekaserver:8761/eureka/
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

  foodcatalogue:
    build:
      context: ../apps/foodCatalogue
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_URL=jdbc:mysql://mysql:3306/restaurantdb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - EUREKA_SERVER_URL=http://eurekaserver:8761/eureka/
    depends_on:
      - eurekaserver
      - mysql 



volumes:
  mysql-data:
  mongo-data: